server:
  port: 8080

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always
management.health.diskspace.enabled: false
management.health.ratelimiters.enabled: false

chucknorris:
  jokes:
    url: https://api.chucknorris.io/jokes

springdoc:
  swagger-ui:
    enabled: true
    path: /

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: FULL
  autoconfiguration:
    jackson:
      enabled: true

logging:
  level:
    com.laughter.joke: DEBUG

resilience4j.ratelimiter:
  configs:
    default:
      limitForPeriod: 2
      limitRefreshPeriod: 5s
      timeoutDuration: 3s
      registerHealthIndicator: true
      eventConsumerBufferSize: 100
  instances:
    norris:
      baseConfig: default

