chucknorris:
  jokes:
    url: https://api.chucknorris.io/jokes

springdoc:
  swagger-ui:
    enabled: true
    path: /

feign:
  client:
    config:
      default:
        connectTimeout: 4000
        readTimeout: 4000
        loggerLevel: FULL
  autoconfiguration:
    jackson:
      enabled: true

logging:
  level:
    com.laughter.joke: DEBUG

resilience4j.ratelimiter:
  instances:
    jokes:
      limitForPeriod: 5
      limitRefreshPeriod: 5s
      timeoutDuration: 10s
      registerHealthIndicator: true
      eventConsumerBufferSize: 100
